services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"  # Open WebUI에 접근할 로컬 포트
    environment:
      - CONNECTIONS=http://pipelines:9099:adsf13@4
    volumes:
      - ./open-webui:/app/backend/data  # Open WebUI 데이터 볼륨
    depends_on:
      - pipelines  # Pipelines 서비스가 먼저 실행되어야 함
    restart: always

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"  # Pipelines에 접근할 로컬 포트
    environment:
      - PIPELINES_API_KEY=adsf13@4
      - PIPELINES_URLS=/app/pipelines/main.py
      - PIPELINES_REQUIREMENTS_PATH=/app/pipelines/requirements.txt
    volumes:
      - ./pipelines:/app/pipelines  # Pipelines 데이터 볼륨
    restart: always